### ISSUE TITLE
using packer-plugin as a alternative to OS Image Builder

### ISSUE THREAD

**Issue by wolfganghuse** [nutanix-cloud-native/cluster-api-provider-nutanix#12]
Hi, as we are also have a packer plugin available for creating OS-Images we could provide an example for using this instead of OS Image Builder.

**Comment by deepakm-ntnx** [comment]
@wolfganghuse could you please provide more info regarding the location of this plugin code and any other relevant details. currently we use this terraform to create capi recommended image. https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/tree/main/tools/imagebuilder

**Comment by deepakm-ntnx** [comment]
https://github.com/kubernetes-sigs/image-builder/pull/921

**Comment by pipoe2h** [comment]
@deepakm-ntnx packer-plugin [here](https://github.com/nutanix-cloud-native/packer-plugin-nutanix)
