### ISSUE TITLE
Deployment fails if there is more than one image with the same name

### ISSUE THREAD

**Issue by pipoe2h** [nutanix-cloud-native/cluster-api-provider-nutanix#260]
/kind bug

**What steps did you take and what happened:**

Deployment fails if there is more than one image with the same name

**What did you expect to happen:**

The cluster object showed as provisioned when it wasn't provisioned. It should show as failed

**Anything else you would like to add:**

Provide an option to pass image UUID if there is an image name overlapping

**Environment:**

- Cluster-api-provider-nutanix version: v1.1.1

**Comment by tuxtof** [comment]
Hi @pipoe2h 

check in the doc here https://opendocs.nutanix.com/capx/v1.1.x/types/nutanix_machine_template/#configuration-parameters

you can already specify an image with his uuid

```
image:
  type: uuid
  uuid: XXXXXXXXX
```

**Comment by tuxtof** [comment]
https://github.com/nutanix-cloud-native/opendocs/pull/41

**Comment by tuxtof** [comment]
merged
