### ISSUE TITLE
make docker-build fails with missing file error message

### ISSUE THREAD

**Issue by rajeevramani** [nutanix-cloud-native/cluster-api-provider-nutanix#54]
Cluster API build bug

**What steps did you take and what happened:**
Follow the instruction mentions [here](https://github.com/rajeevramani/cluster-api-provider-nutanix/blob/main/docs/getting_started.md) under the heading `Developer workflow`. 
When you try the step `make docker-build` you will hit the following issue

```
KO_DOCKER_REPO=ko.local /XXXXX/cluster-api-provider-nutanix/hack/tools/bin/ko-v0.11.2 build -B --platform=linux/amd64,linux/arm64,linux/arm -t latest -L .

bash: /XXXXX/cluster-api-provider-nutanix/hack/tools/bin/ko-v0.11.2: No such file or directory
make: *** [docker-build] Error 127
```
I am using
```
clusterctl version: &version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.4", 

GitCommit:"1c3a1526f101d4b07d2eec757fe75e8701cf6212", GitTreeState:"clean", BuildDate:"", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/amd64"}
```

**What did you expect to happen:**
I expected to see non error logs

For documentation sake it will be useful if screenshots of expected outputs can be included

**Anything else you would like to add:**

_Miscellaneous information that will assist in solving the issue._

**Environment:**

- Cluster-api-provider-nutanix version: 
- Kubernetes version: (use `kubectl version`):  Client Version: v1.24.2
- OS (e.g. from `/etc/os-release`):

**Comment by deepakm-ntnx** [comment]
Thanks @rajeevramani for reporting the issue, its fix is in review here https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/pull/53/files
meanwhile, you can run <pre>make ko</pre> to install ko on your setup.
